
%:
	wget -O $@ "https://github.com/holochain/devhub-dnas/releases/download/v$(VERSION)/$*"
devhub.happ:
	wget -O $@ "https://github.com/holochain/devhub-dnas/releases/download/v$(VERSION)/DevHub.happ"
